import test from "node:test";
import assert from "node:assert/strict";
import { describeDistribution, distributionScale, distributionPosition, habitualPosition, distributionTone, MIN_MATCHES_FOR_HABITUAL_RANGE } from "./distributionStatistics";
import { buildDistributionUniverse, metricComparison, metricDistribution, DISTRIBUTION_METRICS } from "./dashboardDistribution";
import { buildDashboardV2, emptyDashboardScope, referenceScopeForPreset, teamMetricValue, homogeneousComparisonMode } from "./dashboardV2";
import { DashboardMatchRecord } from "./dashboardAnalytics";
import { createLineupInitializedEvent, createLiveThreatEvent } from "./matchEngine";
import { Player } from "../types";

const players: Player[] = Array.from({ length: 5 }, (_, i) => ({ id: `p${i}`, name: `P${i}`, number: i, position: i ? "ALA" : "PORTERO" }));
const scope = () => emptyDashboardScope("club", "team", "season");
function record(id: string, goals: number, shots = goals, venue: "HOME" | "AWAY" = "HOME", opponent = id): DashboardMatchRecord {
  const lineup = createLineupInitializedEvent({ id: `${id}-lineup`, matchId: id, position: { period: 1, minute: 0, order: 0 }, squadPlayerIds: players.map(p => p.id), onCourtPlayerIds: players.map(p => p.id), goalkeeperPlayerId: "p0", now: 1 });
  const events = Array.from({ length: shots }, (_, i) => createLiveThreatEvent({ id: `${id}-${i}`, matchId: id, position: { period: 1, minute: 1 + i / 100, order: i + 1 }, side: "FOR", playerId: "p1", origin: { x: .7, y: .5 }, outcome: i < goals ? "GOL" : "FUERA", phase: "POSITIONAL", now: i + 2 }));
  return { catalog: { matchId: id, clubId: "club", teamId: "team", seasonId: "season", opponent, venue, date: "2026-01-01", status: "FINISHED", updatedAt: 1 }, session: { matchId: id, players, staff: [], period: 2, minute: 20, periodMinutes: {1:20,2:20}, closedPeriods:[1,2], matchFinished: true, events: [lineup,...events], past: [], future: [], lastError:null,persistenceStatus:"saved",lastSavedAt:1 } };
}
const records = () => [record("a",0,0,"HOME","Norte"),record("b",2,4,"AWAY","Norte"),record("c",4,8,"HOME","Sur"),record("d",10,10,"AWAY","Sur")];
test("media, mediana par, cuantiles R-7, desviación poblacional y extremos",()=>{assert.deepEqual(describeDistribution([1,2,3,4]),{n:4,missing:0,mean:2.5,median:2.5,p25:1.75,p75:3.25,stdDev:Math.sqrt(1.25),min:1,max:4});});
test("mediana impar, orden inmutable y repetidos",()=>{const values=[4,1,4,2,4];assert.equal(describeDistribution(values).median,4);assert.equal(describeDistribution(values).p25,2);assert.deepEqual(values,[4,1,4,2,4]);});
test("N=0 y datos ausentes no se convierten en cero",()=>{const s=describeDistribution([null,undefined,NaN,Infinity]);assert.equal(s.n,0);assert.equal(s.missing,4);assert.equal(s.mean,null);assert.equal(s.p25,null);assert.equal(s.stdDev,null);});
test("N=1 tiene dispersión cero y N<4 no ofrece banda sólida",()=>{const s=describeDistribution([7]);assert.equal(s.mean,7);assert.equal(s.p25,7);assert.equal(s.stdDev,0);assert.equal(habitualPosition(7,s),"unavailable");assert.equal(habitualPosition(2,describeDistribution([1,2,3])),"unavailable");assert.equal(MIN_MATCHES_FOR_HABITUAL_RANGE,4);});
test("todos iguales y ceros reales conservados",()=>{const s=describeDistribution([0,0,0,0]);assert.equal(s.n,4);assert.equal(s.p75,0);assert.equal(s.stdDev,0);assert.equal(habitualPosition(0,s),"within");});
test("no se recortan extremos y la media difiere de la mediana",()=>{const s=describeDistribution([1,1,1,1,1000]);assert.equal(s.max,1000);assert.equal(s.mean,200.8);assert.equal(s.median,1);assert.equal(s.p75,1);});
for(const [value,expected] of [[1,"below"],[2.5,"within"],[4,"above"]] as const)test(`microvisualización: ${expected}`,()=>{assert.equal(habitualPosition(value,describeDistribution([1,2,3,4])),expected);});
test("escala incluye referencia, actual fuera de min/max y margen simétrico",()=>{const s=distributionScale([1,4,-20,100]);assert.ok(s.min< -20);assert.ok(s.max>100);assert.ok(distributionPosition(100,s)<100);assert.ok(distributionPosition(-20,s)>0);assert.ok(distributionScale([0,0]).max>distributionScale([0,0]).min);});
for(const [direction,up,down] of [["HIGHER_IS_BETTER","positive","negative"],["LOWER_IS_BETTER","negative","positive"],["NEUTRAL","neutral","neutral"]] as const)test(`polaridad ${direction}`,()=>{assert.equal(distributionTone(5,3,direction),up);assert.equal(distributionTone(1,3,direction),down);assert.equal(distributionTone(null,3,direction),"neutral");});
test("selección actual y referencia temporada son universos separados",()=>{const data=records(),a={...scope(),matchIds:["d"]},r=referenceScopeForPreset(a,"SEASON");const result=metricComparison(buildDistributionUniverse(data,a),buildDistributionUniverse(data,r),"goalsFor","PER_MATCH");assert.equal(result.value,10);assert.equal(result.referenceValue,4);assert.equal(result.current.stats.n,1);assert.equal(result.reference?.stats.n,4);assert.equal(result.reference?.stats.median,3);assert.equal(result.reference?.stats.p75,5.5);});
for(const [preset,ids] of [["HOME",["a","c"]],["AWAY",["b","d"]]] as const)test(`referencia ${preset}`,()=>{const u=buildDistributionUniverse(records(),referenceScopeForPreset(scope(),preset));assert.deepEqual(u.matches.map(x=>x.record.catalog.matchId),ids);});
test("referencia rival y selección CUSTOM respetan scope explícito",()=>{const u=buildDistributionUniverse(records(),{...scope(),rivals:["Norte"],matchIds:["b"]});assert.deepEqual(metricDistribution(u,"goalsFor","PER_MATCH").observations.map(o=>o.value),[2]);});
test("filtros de evento conservan ceros reales y excluyen ratios no calculables",()=>{const u=buildDistributionUniverse(records(),{...scope(),phases:["TRANSITION"]});const count=metricDistribution(u,"goalsFor","PER_MATCH"),ratio=metricDistribution(u,"FOR.conversionPercentage","PER_MATCH");assert.equal(count.stats.n,4);assert.equal(count.stats.mean,0);assert.equal(ratio.stats.n,0);assert.equal(ratio.stats.missing,4);});
test("porcentajes por partido, no cuantiles de numeradores/denominadores ni agregado",()=>{const data=[record("a",1,1),record("b",0,9)];const u=buildDistributionUniverse(data,scope());const c=metricComparison(u,u,"FOR.conversionPercentage","TOTALS");assert.equal(c.value,10);assert.equal(c.current.stats.mean,50);assert.equal(c.current.stats.median,50);assert.equal(c.current.stats.p25,25);assert.equal(c.current.stats.p75,75);});
test("PER_40 usa denominador de cada partido y guarda N/D con cero tiempo",()=>{const r=record("a",2);r.session.periodMinutes={1:10,2:0};r.session.matchFinished=false;r.session.period=1;r.session.minute=10;r.session.closedPeriods=[];const c=metricDistribution(buildDistributionUniverse([r],scope()),"goalsFor","PER_40");assert.equal(c.stats.mean,8);const zero=buildDistributionUniverse([r],{...scope(),playingState:"PJ_CDA"});assert.equal(metricDistribution(zero,"goalsFor","PER_40").stats.n,0);});
test("P2 aplica filtro temporal a la observación de cada partido",()=>{const u=buildDistributionUniverse(records(),{...scope(),period:2});assert.deepEqual(metricDistribution(u,"goalsFor","PER_MATCH").observations.map(o=>o.value),[0,0,0,0]);});
test("extremos identifican todos los partidos empatados",()=>{const d=metricDistribution(buildDistributionUniverse([record("a",2),record("b",2)],scope()),"goalsFor","TOTALS");assert.equal(d.minimumMatches.length,2);assert.equal(d.maximumMatches.length,2);});
test("regresión de comparación: mismos agregados y normalización; datos no mutados",()=>{const data=records(),before=JSON.stringify(data),a=buildDashboardV2(data,scope()),u=buildDistributionUniverse(data,scope());for(const mode of ["TOTALS","PER_MATCH","PER_40"] as const)assert.equal(metricComparison(u,u,"goalsFor",mode).value,teamMetricValue(a,"goalsFor",mode));assert.equal(homogeneousComparisonMode(4,4,"TOTALS"),"PER_MATCH");assert.deepEqual(buildDashboardV2(data,scope()),a);assert.equal(JSON.stringify(data),before);});
test("registro incluye métricas existentes, disciplina, ABP, pérdidas y paradas neutrales",()=>{for(const id of ["goalsFor","goalsAgainst","threatsFor","threatsAgainst","possessionLosses","discipline.for.yellowCards","discipline.against.redCards","abp.ALL.FOR.withShot","phase.POSITIONAL.FOR"])assert.ok(DISTRIBUTION_METRICS[id]);assert.equal(DISTRIBUTION_METRICS['FOR.saves'].direction,"NEUTRAL");assert.equal(DISTRIBUTION_METRICS.goalsAgainst.direction,"LOWER_IS_BETTER");});
