"use client";

import { useMemo, useState } from "react";
import { DashboardMatchRecord } from "../../lib/dashboardAnalytics";
import { DashboardScopeV2 } from "../../lib/dashboardV2";
import { analyzeCombination, buildCombinationsContext, CombinationRow, CombinationSize, compareCombinations, rankCombinations } from "../../lib/dashboardCombinations";
import { Player } from "../../types";
import { PlayerAvatar } from "../player/PlayerAvatar";

const labels = { 2: "PAREJAS", 3: "TRÍOS", 4: "CUARTETOS", 5: "QUINTETOS" };
const number = (value: number | null, signed = false) => value === null ? "N/D" : `${signed && value > 0 ? "+" : ""}${value.toLocaleString("es-ES", { maximumFractionDigits: 1 })}`;
const clock = (minutes: number) => { const seconds = Math.round(minutes * 60); return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, "0")}`; };
const metrics = [ ["goals", "BALANCE GOLES"], ["danger", "BALANCE PELIGRO"], ["gf", "GF"], ["shots", "REMATES"], ["gc", "GC"], ["threats", "AMENAZAS"]] as const;
type SortKey = "minutes" | "matches" | "goals" | "danger" | "deltaGoals" | "deltaDanger" | "gf" | "shots" | "gc" | "threats";
const sortOptions: Array<[SortKey, string]> = [["minutes", "USO / MINUTOS / %"], ["matches", "PJ"], ["goals", "BALANCE GOLES"], ["deltaGoals", "Δ BALANCE GOLES"], ["danger", "BALANCE PELIGRO"], ["deltaDanger", "Δ BALANCE PELIGRO"], ["gf", "GF"], ["shots", "REMATES"], ["gc", "GC"], ["threats", "AMENAZAS"]];
function value(row: CombinationRow, key: SortKey) { return key === "minutes" || key === "matches" ? row[key] : key === "deltaGoals" ? row.differential.goals : key === "deltaDanger" ? row.differential.danger : row.rates[key]; }
function Names({ ids, players }: { ids: string[]; players: Player[] }) {
  const selected = ids.map(id => players.find(p => p.id === id)).filter((p): p is Player => !!p);
  return <span className="block"><span className="flex -space-x-3 pb-2">{selected.map(p => <PlayerAvatar key={p.id} player={p} compact />)}</span><span className="block max-w-64 text-xs font-bold leading-relaxed">{selected.map(p => p.name).join(" · ")}</span></span>;
}
function Sample({ row }: { row: CombinationRow }) { return row.minutes === 0 ? <span className="text-amber-200">SIN MUESTRA CONJUNTA</span> : row.lowSample ? <span className="rounded bg-amber-950 px-2 py-1 text-[10px] font-black text-amber-200">MUESTRA BAJA</span> : null; }
function Picker({ players, size, title, onChoose, onCancel }: { players: Player[]; size: CombinationSize; title: string; onChoose: (ids: string[]) => void; onCancel: () => void }) {
  const [ids, setIds] = useState<string[]>([]);
  const valid = ids.filter(id => players.some(p => p.id === id));
  return <section className="rounded-2xl border border-cyan-800 bg-slate-900 p-4" aria-label={title}><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-black">{title} · {valid.length}/{size}</h3><button type="button" onClick={onCancel} className="min-h-10 px-3 text-xs">CANCELAR</button></div><p className="mb-3 text-xs text-slate-400">Selecciona exactamente {size} jugadores, incluido el portero si lo deseas.</p><div className="flex max-h-64 flex-wrap gap-2 overflow-y-auto">{players.map(p => <button key={p.id} type="button" aria-pressed={valid.includes(p.id)} disabled={!valid.includes(p.id) && valid.length === size} onClick={() => setIds(valid.includes(p.id) ? valid.filter(id => id !== p.id) : [...valid, p.id])} className={`flex min-h-12 items-center gap-2 rounded-xl border px-3 py-2 text-xs disabled:opacity-40 ${valid.includes(p.id) ? "border-cyan-300 bg-cyan-950 text-cyan-100" : "border-slate-700"}`}><PlayerAvatar player={p} compact />{p.name}</button>)}</div><button type="button" disabled={valid.length !== size} onClick={() => onChoose(valid)} className="mt-4 min-h-11 rounded-xl bg-cyan-300 px-5 text-xs font-black text-slate-950 disabled:opacity-40">ANALIZAR COMBINACIÓN</button></section>;
}
function Points({ row }: { row: CombinationRow }) { return <div title="Resultado parcial únicamente durante los minutos en que coincide la combinación. No son puntos reales de clasificación."><strong>{row.points.total}/{row.points.possible} · {number(row.points.perMatch)}/PJ</strong><p className="text-xs text-slate-400">{row.points.positive} positivos · {row.points.draws} empates · {row.points.negative} negativos</p></div>; }

export function DashboardCombinations({ records, scope, canViewIndividualAnalytics = true }: { records: DashboardMatchRecord[]; scope: DashboardScopeV2; canViewIndividualAnalytics?: boolean }) {
  const [size, setSize] = useState<CombinationSize>(2), [sort, setSort] = useState<SortKey>("minutes"), [ascending, setAscending] = useState(false);
  const [selected, setSelected] = useState<string[] | null>(null), [second, setSecond] = useState<string[] | null>(null), [picker, setPicker] = useState<"explore" | "compare" | null>(null);
  const context = useMemo(() => buildCombinationsContext(records, scope), [records, scope]);
  const ranking = useMemo(() => rankCombinations(context, size), [context, size]);
  const ordered = useMemo(() => [...ranking].sort((a, b) => { const x = value(a, sort), y = value(b, sort); return x === null ? y === null ? a.key.localeCompare(b.key) : 1 : y === null ? -1 : (ascending ? x - y : y - x) || a.key.localeCompare(b.key); }), [ranking, sort, ascending]);
  const exists = (ids: string[] | null): ids is string[] => !!ids && ids.every(id => context.players.some(p => p.id === id));
  const row = selected && exists(selected) ? analyzeCombination(context, selected) : null;
  const comparison = row && exists(second) ? compareCombinations(context, row.ids, second) : null;
  if (!canViewIndividualAnalytics) return null;
  const chooseSort = (key: SortKey) => { if (sort === key) setAscending(!ascending); else { setSort(key); setAscending(false); } };
  const open = (ids: string[]) => { setSelected(ids); setSecond(null); setPicker(null); };
  const header = (key: SortKey, title: string) => <th scope="col" aria-sort={sort === key ? ascending ? "ascending" : "descending" : "none"} className="p-2 text-right"><button type="button" className="min-h-10 text-[10px] font-black" onClick={() => chooseSort(key)}>{title} {sort === key ? ascending ? "↑" : "↓" : "↕"}</button></th>;
  const table = (rows: CombinationRow[]) => <div className="overflow-x-auto rounded-2xl border border-slate-800"><table className="w-full min-w-[1050px] text-right text-xs"><thead className="bg-slate-900 text-slate-400"><tr><th rowSpan={2} className="w-60 p-3 text-left">COMBINACIÓN</th><th colSpan={4} className="border-l border-slate-700 p-2 text-center">EXPOSICIÓN</th><th colSpan={2} className="border-l border-slate-700 p-2 text-center">GLOBAL · x40</th><th colSpan={2} className="border-l border-slate-700 p-2 text-center">ATAQUE · x40</th><th colSpan={2} className="border-l border-slate-700 p-2 text-center">DEFENSA · x40</th></tr><tr>{header("minutes", "MIN")}{header("matches", "PJ")}{header("minutes", "% TIEMPO")}<th className="p-2">MIN/PJ</th>{header("goals", "BAL. GOLES")}{header("danger", "BAL. PELIGRO")}{header("gf", "GF")}{header("shots", "REMATES")}{header("gc", "GC")}{header("threats", "AMENAZAS")}</tr></thead><tbody>{rows.map(r => <tr key={r.key} className="border-t border-slate-800 hover:bg-slate-900/70"><th scope="row" className="p-3 text-left"><button type="button" onClick={() => open(r.ids)} className="text-left"><Names ids={r.ids} players={context.players} /></button></th><td className="p-2 font-mono font-bold">{clock(r.minutes)}</td><td className="p-2">{r.matches}</td><td className="p-2">{number(r.percent)}%</td><td className="p-2">{number(r.minutesPerMatch)}</td>{(["goals", "danger"] as const).map(k => <td key={k} className="whitespace-nowrap p-2"><strong className="text-lg">{number(r.rates[k], true)}</strong><div className="text-[10px] text-slate-400">resto {number(r.rest[k], true)}<br/><button type="button" title="Ordenar por diferencial vs RESTO" onClick={() => chooseSort(k === "goals" ? "deltaGoals" : "deltaDanger")}>Δ {number(r.differential[k], true)}</button></div></td>)}{(["gf", "shots", "gc", "threats"] as const).map(k => <td key={k} className="p-2 text-base font-bold">{number(r.rates[k])}</td>)}</tr>)}</tbody></table></div>;
  return <section className="space-y-4" aria-label="Combinaciones"><header className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">COMBINACIONES</h2><p className="text-xs text-slate-400">{clock(context.minutes)} válidos · {context.matches.length} PJ · métricas x40 · descriptivo, no causal</p></div>{!selected && <button type="button" onClick={() => setPicker("explore")} className="min-h-11 rounded-xl bg-cyan-300 px-4 text-xs font-black text-slate-950">EXPLORAR COMBINACIÓN</button>}</header>
    <details className="text-xs text-slate-400"><summary className="cursor-pointer">Cómo leer JUNTOS, RESTO y DIFERENCIAL</summary><p className="mt-2">RESTO: minutos válidos del mismo contexto sin la combinación completa. DIFERENCIAL = JUNTOS − RESTO. Peligro: remates a favor − amenazas recibidas; mide volumen, no calidad. Los filtros de eventos mantienen los minutos y no alteran PUNTOS COMBINACIÓN. El reloj deportivo tiene precisión de minuto.</p></details>
    {context.excludedMinutes > 0 && <p role="status" className="rounded-xl bg-amber-950/50 p-3 text-xs text-amber-200">{clock(context.excludedMinutes)} excluidos por alineación incompleta o no fiable; no forman parte de JUNTOS ni RESTO.</p>}
    {context.minutes === 0 && <p className="rounded-xl border border-dashed border-slate-700 p-5">SIN TIEMPO VÁLIDO EN ESTE CONTEXTO</p>}
    {!selected && <><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap gap-1">{([2, 3, 4, 5] as CombinationSize[]).map(n => <button type="button" key={n} aria-pressed={size === n} onClick={() => { setSize(n); setPicker(null); }} className={`min-h-11 rounded-xl px-3 text-xs font-black ${size === n ? "bg-cyan-300 text-slate-950" : "bg-slate-800"}`}>{labels[n]}</button>)}</div><label className="text-[10px] text-slate-400">ORDEN <select aria-label="Orden de combinaciones" value={sort} onChange={e => { setSort(e.target.value as SortKey); setAscending(false); }} className="min-h-10 rounded-xl bg-slate-800 p-2 text-xs">{sortOptions.map(([k, text]) => <option key={k} value={k}>{text}</option>)}</select></label></div><h3 className="text-xs font-black text-slate-300">COMBINACIONES CON MUESTRA SUFICIENTE</h3>{ordered.some(r => !r.lowSample) ? table(ordered.filter(r => !r.lowSample)) : <p className="text-sm text-slate-500">Sin combinaciones con muestra suficiente. Puedes explorar todas las observadas abajo.</p>}<details className="rounded-2xl border border-amber-900/50 p-3"><summary className="cursor-pointer text-xs font-black text-amber-200">MUESTRA BAJA · {ordered.filter(r => r.lowSample).length} combinaciones ▾</summary><div className="mt-3">{table(ordered.filter(r => r.lowSample))}</div></details></>}
    {selected && <button type="button" onClick={() => { setSelected(null); setSecond(null); setPicker(null); }} className="min-h-11 rounded-xl bg-slate-800 px-4 text-xs font-black">← VOLVER AL RANKING</button>}
    {selected && !row && <p>La selección no pertenece al contexto actual. Vuelve al ranking para elegir otra combinación.</p>}
    {row && <><div className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-slate-700 bg-slate-900 p-4"><Names ids={row.ids} players={context.players}/><div><strong className="text-xl">{clock(row.minutes)} · {row.matches} PJ · {number(row.percent)}%</strong><p className="text-xs text-slate-400">{number(row.minutesPerMatch)} min/PJ</p><Sample row={row}/></div><button type="button" onClick={() => setPicker("compare")} className="min-h-11 rounded-xl bg-cyan-300 px-4 text-xs font-black text-slate-950">COMPARAR</button></div>
      {row.minutes > 0 && <><div className="overflow-x-auto rounded-2xl border border-slate-800"><table className="w-full text-right"><thead className="bg-slate-900 text-xs"><tr><th className="p-3 text-left">MÉTRICA x40</th><th className="p-3">JUNTOS</th><th className="p-3">RESTO</th><th className="p-3">DIFERENCIAL</th></tr></thead><tbody>{metrics.map(([k, text]) => <tr key={k} className="border-t border-slate-800"><th className="p-3 text-left text-xs" title={k === "danger" ? "Remates a favor − amenazas recibidas" : undefined}>{text}</th><td className="p-3 text-xl font-black">{number(row.rates[k], k === "goals" || k === "danger")}</td><td className="p-3 text-sm text-slate-400">{number(row.rest[k])}</td><td className="p-3 font-bold">{k === "goals" || k === "danger" ? number(row.differential[k], true) : "—"}</td></tr>)}</tbody></table></div><section className="rounded-2xl border border-slate-800 p-4"><h3 className="mb-2 text-xs font-black">PUNTOS COMBINACIÓN</h3><Points row={row}/><p className="mt-2 text-xs text-slate-400">Resultado parcial únicamente durante los minutos en que coincide la combinación. No son puntos reales de clasificación.</p></section><section><h3 className="mb-2 text-xs font-black">PARTIDO A PARTIDO</h3><div className="overflow-x-auto"><table className="w-full min-w-[540px] text-right text-xs"><thead><tr><th className="p-2 text-left">PARTIDO</th><th>MIN</th><th>% CONTEXTO</th><th>GF–GC</th><th>BAL. PELIGRO</th></tr></thead><tbody>{row.byMatch.map(m => <tr key={m.matchId} className="border-t border-slate-800"><th className="p-3 text-left">{m.date} · {m.opponent}</th><td>{clock(m.minutes)}</td><td>{number(m.minutes / m.contextMinutes * 100)}%</td><td>{m.counts.gf}–{m.counts.gc}</td><td>{number(m.counts.shots - m.counts.threats, true)}</td></tr>)}</tbody></table></div></section>{row.ids.length < 5 && <section><h3 className="mb-3 text-xs font-black">QUINTETOS MÁS HABITUALES CON ESTA COMBINACIÓN</h3><div className="grid gap-2 md:grid-cols-2">{row.quintets.slice(0, 6).map(q => <div key={q.ids.join("|")} className="flex items-center justify-between gap-3 rounded-xl bg-slate-900 p-3"><Names ids={q.ids} players={context.players}/><span className="whitespace-nowrap text-sm font-bold">{clock(q.minutes)} · {number(q.percent)}%</span></div>)}</div></section>}</>}
    </>}
    {picker && <Picker key={`${picker}-${size}`} title={picker === "compare" ? "COMPARAR CON" : "EXPLORAR COMBINACIÓN"} players={context.players} size={size} onCancel={() => setPicker(null)} onChoose={ids => { if (picker === "compare") { setSecond(ids); setPicker(null); } else open(ids); }}/>}
    {comparison && <section className="space-y-3 rounded-2xl border border-cyan-900 p-3"><div className="flex items-center justify-between"><h3 className="text-xs font-black">COMPARADOR · MISMO CONTEXTO · NO CAUSAL</h3><button type="button" onClick={() => setSecond(null)} className="min-h-10 px-3 text-xs">CERRAR</button></div><div className="grid grid-cols-2 gap-3">{[comparison.a, comparison.b].map((r, i) => <div key={i} className="rounded-xl bg-slate-900 p-3"><b>{i === 0 ? "A" : "B"}</b><Names ids={r.ids} players={context.players}/><Sample row={r}/></div>)}</div><div className="overflow-x-auto"><table className="w-full min-w-[490px] text-right text-sm"><thead><tr><th className="p-2 text-left">MÉTRICA</th><th>A</th><th>B</th><th>A − B</th></tr></thead><tbody>{[["Minutos", comparison.a.minutes, comparison.b.minutes], ["PJ", comparison.a.matches, comparison.b.matches], ["% tiempo", comparison.a.percent, comparison.b.percent], ["min/PJ", comparison.a.minutesPerMatch, comparison.b.minutesPerMatch], ...metrics.map(([k, text]) => [text + " x40", comparison.a.rates[k], comparison.b.rates[k]]), ["Δ goles vs RESTO", comparison.a.differential.goals, comparison.b.differential.goals], ["Δ peligro vs RESTO", comparison.a.differential.danger, comparison.b.differential.danger], ["Puntos combinación / PJ", comparison.a.points.perMatch, comparison.b.points.perMatch]].map(([label, a, b]) => <tr key={String(label)} className="border-t border-slate-800"><th className="p-2 text-left text-xs">{label}</th><td>{number(a as number | null)}</td><td>{number(b as number | null)}</td><td>{typeof a === "number" && typeof b === "number" ? number(a - b, true) : "N/D"}</td></tr>)}</tbody></table></div><div className="grid grid-cols-2 gap-3">{[comparison.a, comparison.b].map((r, i) => <div key={i}><h4 className="text-xs font-black">PUNTOS COMBINACIÓN {i === 0 ? "A" : "B"}</h4><Points row={r}/></div>)}</div></section>}
  </section>;
}
