import { PlayerAnalysis } from "../../lib/dashboardAnalysis";
import { MetricDirection } from "../../lib/dashboardMetricDefinitions";
import { PlayerPhotoCard } from "../player/PlayerPhotoCard";

type Row = { label: string; value: (player: PlayerAnalysis) => number | null; direction: MetricDirection };
const groups: Array<[string, Row[]]> = [
  ["PARTICIPACIÓN", [{ label: "PARTIDOS", value: (p) => p.matches, direction: "NEUTRAL" }, { label: "MINUTOS", value: (p) => p.minutes, direction: "NEUTRAL" }, { label: "MIN/PARTIDO", value: (p) => p.averageMinutes, direction: "NEUTRAL" }]],
  ["PRODUCCIÓN", [{ label: "GOLES", value: (p) => p.goals, direction: "HIGHER_IS_BETTER" }, { label: "GOLES/PARTIDO", value: (p) => p.goalsPerMatch, direction: "HIGHER_IS_BETTER" }, { label: "GOLES/40", value: (p) => p.goals40, direction: "HIGHER_IS_BETTER" }, { label: "ASISTENCIAS", value: (p) => p.assists, direction: "HIGHER_IS_BETTER" }, { label: "ASIST./PARTIDO", value: (p) => p.assistsPerMatch, direction: "HIGHER_IS_BETTER" }, { label: "ASIST./40", value: (p) => p.assists40, direction: "HIGHER_IS_BETTER" }, { label: "REMATES", value: (p) => p.ownThreats, direction: "HIGHER_IS_BETTER" }, { label: "REMATES/PARTIDO", value: (p) => p.ownThreatsPerMatch, direction: "HIGHER_IS_BETTER" }, { label: "REMATES/40", value: (p) => p.ownThreats40, direction: "HIGHER_IS_BETTER" }, { label: "REMATES A PUERTA", value: (p) => p.ownOnTarget, direction: "HIGHER_IS_BETTER" }, { label: "% A PUERTA", value: (p) => p.ownOnTargetPercentage, direction: "HIGHER_IS_BETTER" }, { label: "REMATES CERCANOS", value: (p) => p.ownNear, direction: "NEUTRAL" }]],
  ["EN PISTA", [{ label: "GF", value: (p) => p.onCourt.goalsFor, direction: "HIGHER_IS_BETTER" }, { label: "GC", value: (p) => p.onCourt.goalsAgainst, direction: "LOWER_IS_BETTER" }, { label: "DIF. GOLES", value: (p) => p.onCourt.goalDifference, direction: "HIGHER_IS_BETTER" }, { label: "REMATES EQUIPO", value: (p) => p.onCourt.threatsFor, direction: "HIGHER_IS_BETTER" }, { label: "AMENAZAS", value: (p) => p.onCourt.threatsAgainst, direction: "LOWER_IS_BETTER" }, { label: "REMATES EQUIPO/40", value: (p) => p.onCourt.threatsFor40, direction: "HIGHER_IS_BETTER" }, { label: "AMENAZAS/40", value: (p) => p.onCourt.threatsAgainst40, direction: "LOWER_IS_BETTER" }, { label: "REMATES A PUERTA", value: (p) => p.onCourt.threatsForOnTarget, direction: "HIGHER_IS_BETTER" }, { label: "AMENAZAS A PUERTA", value: (p) => p.onCourt.threatsAgainstOnTarget, direction: "LOWER_IS_BETTER" }, { label: "REMATES CERCANOS", value: (p) => p.onCourt.threatsForNear, direction: "NEUTRAL" }, { label: "AMENAZAS CERCANAS", value: (p) => p.onCourt.threatsAgainstNear, direction: "LOWER_IS_BETTER" }, { label: "PTS EN PISTA", value: (p) => p.onCourtPoints, direction: "HIGHER_IS_BETTER" }, { label: "PTS/PARTIDO", value: (p) => p.onCourtPointsPerMatch, direction: "HIGHER_IS_BETTER" }, { label: "MIN. CLAVE", value: (p) => p.keyMinutes, direction: "NEUTRAL" }, { label: "MIN. ORO", value: (p) => p.goldMinutes, direction: "NEUTRAL" }]],
  ["BALANCES Y CONTEXTO", [{ label: "BALANCE REM/AME", value: (p) => p.onCourt.threatsFor - p.onCourt.threatsAgainst, direction: "HIGHER_IS_BETTER" }, { label: "BALANCE A PUERTA", value: (p) => p.onCourt.threatsForOnTarget - p.onCourt.threatsAgainstOnTarget, direction: "HIGHER_IS_BETTER" }, { label: "BALANCE CERCANO", value: (p) => p.onCourt.threatsForNear - p.onCourt.threatsAgainstNear, direction: "HIGHER_IS_BETTER" }, { label: "MIN. CLAVE", value: (p) => p.keyMinutes, direction: "NEUTRAL" }, { label: "% CLAVE", value: (p) => p.keyMinutesPercentage, direction: "NEUTRAL" }, { label: "MIN. ORO", value: (p) => p.goldMinutes, direction: "NEUTRAL" }, { label: "% ORO", value: (p) => p.goldMinutesPercentage, direction: "NEUTRAL" }]],
  ["DISCIPLINA", [{ label: "FC", value: (p) => p.foulsCommitted, direction: "LOWER_IS_BETTER" }, { label: "FR", value: (p) => p.foulsReceived, direction: "NEUTRAL" }, { label: "FC CRÍTICAS", value: (p) => p.criticalFoulsCommitted, direction: "LOWER_IS_BETTER" }, { label: "FR CRÍTICAS", value: (p) => p.criticalFoulsReceived, direction: "NEUTRAL" }]],
];

export function PlayerComparisonPanel({ player, opponent, population, opponentLabel }: { player: PlayerAnalysis; opponent?: PlayerAnalysis; population: PlayerAnalysis[]; opponentLabel: string }) {
  const mean = (row: Row) => { const values = population.map(row.value).filter((value): value is number => value !== null); return values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : null; };
  return <section className="space-y-4 rounded-3xl border border-slate-700 bg-slate-900 p-4"><header className="grid grid-cols-[1fr_auto_1fr] items-center gap-3"><Identity player={player}/><span className="text-[10px] font-black text-slate-600">VS</span>{opponent ? <Identity player={opponent} right/> : <strong className="text-right text-sm text-amber-200">{opponentLabel}</strong>}</header>{groups.map(([title, rows]) => <div key={title}><h3 className="mb-2 text-[9px] font-black tracking-[.16em] text-slate-500">{title}</h3><div className="space-y-1">{rows.map((row) => { const left = row.value(player); const right = opponent ? row.value(opponent) : mean(row); const winner = better(left, right, row.direction); return <div key={row.label} className="grid grid-cols-[1fr_8rem_1fr] items-center gap-2 rounded-xl bg-slate-950 px-3 py-2"><strong className={`text-right ${winner === "LEFT" ? "text-emerald-300" : ""}`}>{format(left)}{winner === "LEFT" ? " · mejor" : ""}</strong><span className="text-center text-[9px] font-black text-slate-400">{row.label}</span><strong className={winner === "RIGHT" ? "text-emerald-300" : ""}>{format(right)}{winner === "RIGHT" ? " · mejor" : ""}</strong></div>; })}</div></div>)}</section>;
}

function Identity({ player, right }: { player: PlayerAnalysis; right?: boolean }) { return <div className={`flex items-center gap-2 ${right ? "flex-row-reverse text-right" : ""}`}><PlayerPhotoCard player={{ id: player.playerId, name: player.name, number: player.number, photoUrl: player.photoUrl }} className="h-12 w-12 shrink-0 rounded-full"/><span><strong className="block text-sm">{player.name}</strong><small className="text-slate-500">#{player.number}</small></span></div>; }
function format(value: number | null) { return value === null ? "N/D" : Number.isInteger(value) ? String(value) : value.toFixed(1).replace(".", ","); }
function better(left: number | null, right: number | null, direction: MetricDirection) { if (left === null || right === null || direction === "NEUTRAL" || left === right) return "NONE"; return (left > right) === (direction === "HIGHER_IS_BETTER") ? "LEFT" : "RIGHT"; }
